### ISSUE TITLE
add an option that allows disabling to ever write to the media file

### ISSUE THREAD

**Issue by calestyo** [mar04/chapters_for_mpv#1]
Hey.

It would be nice if there was an option that allows to disable that the tool ever tries to write to the media file (I mean writing the chapters into that).<br>
Simply to make sure not to change pristine files. Perhaps this should even be the default?

https://github.com/mar04/chapters_for_mpv/blob/78a8513e417daef4aff1a8fb2bba20a804167a18/chapters.lua#L589
Perhaps something that simply disables the key binding?

Thanks,
Chris

**Comment by mar04** [comment]
Well that is the case already - the function is only ever called through the keybinding and it is not bound to any key until the user creates the binding in his input.conf.

**Comment by calestyo** [comment]
Ah, I see. Thanks. Closing.
