### ISSUE TITLE
possible failures when multiple media files with different extensions

### ISSUE THREAD

**Issue by calestyo** [mar04/chapters_for_mpv#2]
Hey.

In numerous places through the script, you do something like:
https://github.com/mar04/chapters_for_mpv/blob/78a8513e417daef4aff1a8fb2bba20a804167a18/chapters.lua#L467
I.e. take the files full path, remove the extension and add `.ffmetadata`.

Isn't that going to fail as soon as there are multiple media files in the same directory with the same name without extension, e.g.
`video.mov` and `video.mp4`?

Care would also need to be taken, as to what `mp.get_property("filename/no-ext")` actually gives, e.g. if there are "multiple extensions like in `video.mov.gpg` or so.

Thanks,
Chris.

**Comment by calestyo** [comment]
Could that:
https://github.com/mar04/chapters_for_mpv/blob/78a8513e417daef4aff1a8fb2bba20a804167a18/chapters.lua#L527
prone to files that have multiple extensions?

**Comment by mar04** [comment]
> I.e. take the files full path, remove the extension and add `.ffmetadata`.
> 
> Isn't that going to fail as soon as there are multiple media files in the same directory with the same name without extension, e.g. `video.mov` and `video.mp4`?

You're right, I guess stripping the extension is not the best idea, and the solution would be to simply append '.ffmetadata'.

**Comment by mar04** [comment]
> Could that:
> 
> https://github.com/mar04/chapters_for_mpv/blob/78a8513e417daef4aff1a8fb2bba20a804167a18/chapters.lua#L527
> 
> prone to files that have multiple extensions?

No, I don't think so.

**Comment by calestyo** [comment]
thx.
