### ISSUE TITLE
Autoload doesn't work

### ISSUE THREAD

**Issue by GoodTimesAhead** [mar04/chapters_for_mpv#25]
It seems that the on_load hook doesn't run.

I tried

`mp.register_event("file-loaded", load_chapters)`

which runs the function but doesn't load the chapters.

**Comment by mar04** [comment]
run mpv in a terminal with `--msg-level=chapters=debug` and post the output here

**Comment by mrfragger** [comment]
this is how I load subtitles...so maybe try mp.commandv perhaps

    local sub13 = io.open(movie_path.."_tempm"..sub_ext, "r")

          for line in sub13:lines() do
            local replace_line = string.gsub(line, "XZSAWQ", ",")     
                demofont_file:write(replace_line .. "\n")
                      end 


      local demofont_new = (movie_path..".demofont"..sub_ext)

      mp.osd_message("Sub converted to DemoFont")
      print("Sub converted to DemoFont")
      mp.commandv('sub-add', demofont_new)
      os.remove(demofont_new)

**Comment by GoodTimesAhead** [comment]
```
[chapters] Loading lua script C:\Users\User\AppData\Roaming/mpv/scripts/chapters.lua...
[chapters] loading mp.defaults
[chapters] loading file C:\Users\User\AppData\Roaming/mpv/scripts/chapters.lua
[chapters] reading options for chapters
[chapters] Opened config file script-opts/chapters.conf.
[chapters] options: {"pause_on_input" = false, "autoload" = true, "autosave" = false, "global_chapters" = false, "chapters_dir" = "C:\Users\User\AppData\Roaming/mpv/chapters", "ask_for_title" = false, "placeholder_title" = "", "hash" = false}
● Video  --vid=1  (h264 1280x720 30 fps) [default]
● Audio  --aid=1  (aac 2ch 44100 Hz 128 kbps) [default]
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:16 / 01:03:09 (0%) A-V:  0.000
Exiting... (Quit)
[chapters] Exiting..
```
I rolled back from mpv v0.39.0-325-gd66ed2d8 to mpv v0.39.0-221-gc5561b8e and it's working again

```
[chapters] Loading lua script C:\Users\User\AppData\Roaming/mpv/scripts/chapters.lua...
[chapters] loading mp.defaults
[chapters] loading file C:\Users\User\AppData\Roaming/mpv/scripts/chapters.lua
[chapters] reading options for chapters
[chapters] Opened config file script-opts/chapters.conf.
[chapters] options: {"pause_on_input" = false, "autoload" = true, "autosave" = false, "global_chapters" = false, "chapters_dir" = "C:\Users\User\AppData\Roaming/mpv/chapters", "ask_for_title" = false, "placeholder_title" = "", "hash" = false}
[chapters] looking for: ./vid.mp4.ffmetadata
[chapters] found in the local directory, loading..
● Video  --vid=1  (h264 1280x720 30 fps) [default]
● Audio  --aid=1  (aac 2ch 44100 Hz 128 kbps) [default]
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:14 / 01:03:09 (0%) A-V:  0.000
Exiting... (Quit)
```

**Comment by mar04** [comment]
I can confirm that it's not working in that build, at least on Windows. For now I'll assume that it's a bug in mpv, but maybe they changed some API and the script will need adjustments - we'll see.

**Comment by mar04** [comment]
should be fixed, let me know if it's still not working
